version: '3.5'

services:
  mysql:
    image: mysql:5.7
    networks:
      - app-manager-network
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=app-manager
    restart: on-failure

  service:
    build:
      context: ./
      args:
        JAR_FILE: ./target/app-manager-1.0-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=jdbc:mysql://mysql:3306/app-manager?useTimezone=true&serverTimezone=UTC&useSSL=false
      - DB_USERNAME:admin
      - DB_PASSWORD:admin
    networks:
      - app-manager-network
    depends_on:
      - mysql
    restart: on-failure

networks:
  app-manager-network:
    driver: bridge